// Package aws enumerates TLS certificates from AWS, read-only.
//
// # Why this is a separate binary
//
// The AWS SDK brings roughly 30 modules. `cmd/certscan` — the thing a prospect
// runs in the first ten minutes — has ZERO runtime dependencies, and "read the
// source, it has no dependencies" is worth a great deal in a first security
// review. Wiring the SDK into it would trade that for a feature not everyone
// uses.
//
// project_1_security_model.md §6 anticipated exactly this: "if binary size or
// dependency count becomes a review objection, move cloud and Kubernetes
// enumeration into a separate optional binary rather than compromising the core
// scanner's minimalism." Thirty modules for an optional feature is that
// objection, so `cmd/certscan-aws` is that binary. Both ship together.
//
// # What it does
//
// It calls eleven read-only APIs, listed in RequiredActions, and returns
// certificate metadata. It performs no write of any kind, and a test fails the
// build if the policy file gains a non-read verb.
//
// # Why ACM enumeration matters more than it looks
//
// The wedge is "here is how many certificates you are not tracking". If a scan
// returns 400 certificates and the customer says "most of those are ACM, we
// know about them", the number is worthless. Being able to subtract ACM
// automatically is what makes the demo survive first contact — which is why
// AWS is the first integration rather than Kubernetes.
package aws

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	awssdk "github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/retry"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials/stscreds"
	"github.com/aws/aws-sdk-go-v2/service/sts"
	"github.com/aws/smithy-go"

	"github.com/certwatch/certwatch/pkg/model"
)

// RequiredActions is the complete list of IAM actions this package calls.
//
// It is the single source of truth: a test asserts the policy file grants
// exactly these and nothing more, so the policy cannot drift wider than the
// code — and a customer following our instructions never gets AccessDenied for
// something we forgot to document.
func RequiredActions() []string {
	return []string{
		"acm:ListCertificates",
		"acm:DescribeCertificate",
		"acm:ListTagsForCertificate",
		"elasticloadbalancing:DescribeLoadBalancers",
		"elasticloadbalancing:DescribeListeners",
		"elasticloadbalancing:DescribeListenerCertificates",
		"cloudfront:ListDistributions",
		"cloudfront:GetDistributionConfig",
		"iam:ListServerCertificates",
		"iam:GetServerCertificate",
		"apigateway:GET",
	}
}

// Rate limiting. AWS does not publish hard numbers for most of these, so the
// design is conservative: cloud enumeration is DISCOVERY, not verification.
// Running it hourly gains nothing — ACM does not change hourly — and burns the
// customer's API budget, which is a shared resource their other teams notice.
const (
	RequestsPerSecond = 5
	MaxRetries        = 5
	SweepInterval     = 6 * time.Hour
	MaxCertsPerSweep  = 50_000
)

// Options configure an enumeration.
type Options struct {
	// RoleARN is assumed using the collector's OWN credentials. The control
	// plane stores no AWS credentials, ever.
	RoleARN string
	// ExternalID is the confused-deputy defence. Generated by us, shown once,
	// required in the customer's trust policy.
	ExternalID string
	Regions    []string
	// Endpoint overrides the AWS endpoint, for LocalStack in tests.
	Endpoint string
}

// CoverageGap records an API call that was refused or failed.
//
// Gaps are FIRST CLASS, not an error return. A partial enumeration presented as
// complete is the worst failure this product can have, because the customer
// will believe it — so every gap is carried through to the report and shown.
type CoverageGap struct {
	Region  string
	Service string
	Call    string
	Reason  string
}

func (g CoverageGap) String() string {
	return fmt.Sprintf("%s/%s %s: %s", g.Region, g.Service, g.Call, g.Reason)
}

// Result is what an enumeration found, and what it could not see.
type Result struct {
	Certificates []Finding
	Gaps         []CoverageGap
	Regions      []string
	AccountID    string
	Truncated    bool
}

// Finding is one certificate discovered through an AWS API.
type Finding struct {
	// Certificate is populated only when a body was available (IAM server
	// certificates). For ACM, only metadata is available by design, because
	// acm:GetCertificate is deliberately not requested.
	Certificate *model.Certificate `json:"certificate,omitempty"`

	Source       string    `json:"source"` // acm | iam | elb | cloudfront | apigateway
	ARN          string    `json:"arn,omitempty"`
	Region       string    `json:"region"`
	DomainName   string    `json:"domain_name,omitempty"`
	SANs         []string  `json:"sans,omitempty"`
	Issuer       string    `json:"issuer,omitempty"`
	NotBefore    time.Time `json:"not_before,omitempty"`
	NotAfter     time.Time `json:"not_after,omitempty"`
	KeyAlgorithm string    `json:"key_algorithm,omitempty"`
	Status       string    `json:"status,omitempty"`
	// InUseBy is the resources ACM says are using this certificate. It is the
	// most useful field in the whole enumeration: it turns an inventory into an
	// answer about blast radius.
	InUseBy []string `json:"in_use_by,omitempty"`
	// Endpoints are the host:port targets this certificate implies, which the
	// network scanner can then verify against reality.
	Endpoints []string          `json:"endpoints,omitempty"`
	Tags      map[string]string `json:"tags,omitempty"`
}

// Enumerator holds the assumed-role configuration.
type Enumerator struct {
	opts Options
	cfg  awssdk.Config
}

// New assumes the customer's role and returns an enumerator.
//
// The collector uses its OWN instance credentials to assume the role. Nothing
// about the customer's credentials is ever transmitted to or stored by the
// control plane — which is why this product needs no secret-management
// subsystem at all.
func New(ctx context.Context, opts Options) (*Enumerator, error) {
	if opts.RoleARN == "" {
		return nil, errors.New("aws: a role ARN is required")
	}
	if opts.ExternalID == "" {
		return nil, errors.New("aws: an external ID is required (it is the confused-deputy defence)")
	}
	if len(opts.Regions) == 0 {
		return nil, errors.New("aws: at least one region is required")
	}

	base, err := config.LoadDefaultConfig(ctx,
		config.WithRegion(opts.Regions[0]),
		// Adaptive retry backs off when AWS throttles rather than hammering a
		// shared resource the customer's other teams are also using.
		config.WithRetryer(func() awssdk.Retryer {
			return retry.NewAdaptiveMode(func(o *retry.AdaptiveModeOptions) {
				o.StandardOptions = append(o.StandardOptions, func(so *retry.StandardOptions) {
					so.MaxAttempts = MaxRetries
				})
			})
		}),
	)
	if err != nil {
		return nil, fmt.Errorf("aws: loading collector credentials: %w", err)
	}
	if opts.Endpoint != "" {
		base.BaseEndpoint = awssdk.String(opts.Endpoint)
	}

	stsClient := sts.NewFromConfig(base)
	provider := stscreds.NewAssumeRoleProvider(stsClient, opts.RoleARN, func(o *stscreds.AssumeRoleOptions) {
		o.ExternalID = awssdk.String(opts.ExternalID)
		o.RoleSessionName = "certwatch-discovery"
	})
	base.Credentials = awssdk.NewCredentialsCache(provider)

	return &Enumerator{opts: opts, cfg: base}, nil
}

// regionConfig clones the base config for one region.
func (e *Enumerator) regionConfig(region string) awssdk.Config {
	c := e.cfg.Copy()
	c.Region = region
	if e.opts.Endpoint != "" {
		c.BaseEndpoint = awssdk.String(e.opts.Endpoint)
	}
	return c
}

// describeFailure turns an AWS error into a coverage gap, or reports that it is
// fatal.
//
// AccessDenied on ONE call is recorded and enumeration continues: a customer
// who granted nine of eleven actions should still get nine actions' worth of
// findings, with the two gaps visible. Refusing everything would punish them
// for a partial grant and tell them nothing about what they are missing.
func describeFailure(region, service, call string, err error) (CoverageGap, bool) {
	if err == nil {
		return CoverageGap{}, false
	}
	var ae smithy.APIError
	reason := err.Error()
	if errors.As(err, &ae) {
		switch ae.ErrorCode() {
		case "AccessDenied", "AccessDeniedException", "UnauthorizedOperation", "NotAuthorized":
			reason = "access denied — this permission was not granted, so these resources are not covered"
		case "Throttling", "ThrottlingException", "RequestLimitExceeded", "TooManyRequestsException":
			reason = "throttled after retries — deferred to the next sweep"
		case "InvalidClientTokenId", "UnrecognizedClientException", "SignatureDoesNotMatch":
			reason = "credentials were rejected (a clock skew on the collector host presents this way)"
		case "OptInRequired", "UnsupportedOperation":
			reason = "this region is not enabled for the account"
		default:
			reason = ae.ErrorCode() + ": " + ae.ErrorMessage()
		}
	}
	return CoverageGap{Region: region, Service: service, Call: call, Reason: reason}, true
}

// dedupeEndpoints normalises and sorts an endpoint list.
func dedupeEndpoints(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		s = strings.ToLower(strings.TrimSpace(s))
		if s != "" && !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}
