// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dueEndpoints = `-- name: DueEndpoints :many
SELECT e.id::text AS id
  FROM endpoints e
  LEFT JOIN endpoint_state s ON s.endpoint_id = e.id
 WHERE e.disabled_at IS NULL
   AND (s.next_check_at IS NULL OR s.next_check_at <= $1::timestamptz)
 ORDER BY COALESCE(s.next_check_at, 'epoch'::timestamptz)
 LIMIT $2::int
`

type DueEndpointsParams struct {
	Now pgtype.Timestamptz
	Lim int32
}

func (q *Queries) DueEndpoints(ctx context.Context, arg DueEndpointsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, dueEndpoints, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionsForEndpoint = `-- name: TransitionsForEndpoint :many

SELECT at,
       kind,
       COALESCE(to_status::text, '')::text           AS to_status,
       COALESCE(outcome::text, '')::text             AS outcome,
       COALESCE(sub_reason, '')::text                AS sub_reason,
       COALESCE(previous_sub_reason, '')::text       AS previous_sub_reason,
       severity::text                                AS severity,
       COALESCE(summary, '')::text                   AS summary,
       observations
  FROM drift_events
 WHERE endpoint_id = $1::uuid
 ORDER BY at DESC, id DESC
 LIMIT $2::int
`

type TransitionsForEndpointParams struct {
	EndpointID pgtype.UUID
	Lim        int32
}

type TransitionsForEndpointRow struct {
	At                pgtype.Timestamptz
	Kind              string
	ToStatus          string
	Outcome           string
	SubReason         string
	PreviousSubReason string
	Severity          string
	Summary           string
	Observations      int32
}

// History reads. Run inside a tenant transaction; RLS scopes every row.
func (q *Queries) TransitionsForEndpoint(ctx context.Context, arg TransitionsForEndpointParams) ([]TransitionsForEndpointRow, error) {
	rows, err := q.db.Query(ctx, transitionsForEndpoint, arg.EndpointID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransitionsForEndpointRow{}
	for rows.Next() {
		var i TransitionsForEndpointRow
		if err := rows.Scan(
			&i.At,
			&i.Kind,
			&i.ToStatus,
			&i.Outcome,
			&i.SubReason,
			&i.PreviousSubReason,
			&i.Severity,
			&i.Summary,
			&i.Observations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
