// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type CollectorStatus string

const (
	CollectorStatusActive  CollectorStatus = "active"
	CollectorStatusSilent  CollectorStatus = "silent"
	CollectorStatusRevoked CollectorStatus = "revoked"
)

func (e *CollectorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CollectorStatus(s)
	case string:
		*e = CollectorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CollectorStatus: %T", src)
	}
	return nil
}

type NullCollectorStatus struct {
	CollectorStatus CollectorStatus
	Valid           bool // Valid is true if CollectorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCollectorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CollectorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CollectorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCollectorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CollectorStatus), nil
}

type CredentialKind string

const (
	CredentialKindX509    CredentialKind = "x509"
	CredentialKindSshCert CredentialKind = "ssh_cert"
	CredentialKindSecret  CredentialKind = "secret"
)

func (e *CredentialKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CredentialKind(s)
	case string:
		*e = CredentialKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CredentialKind: %T", src)
	}
	return nil
}

type NullCredentialKind struct {
	CredentialKind CredentialKind
	Valid          bool // Valid is true if CredentialKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCredentialKind) Scan(value interface{}) error {
	if value == nil {
		ns.CredentialKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CredentialKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCredentialKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CredentialKind), nil
}

type ExpectationMode string

const (
	ExpectationModePinned ExpectationMode = "pinned"
	ExpectationModePolicy ExpectationMode = "policy"
)

func (e *ExpectationMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExpectationMode(s)
	case string:
		*e = ExpectationMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ExpectationMode: %T", src)
	}
	return nil
}

type NullExpectationMode struct {
	ExpectationMode ExpectationMode
	Valid           bool // Valid is true if ExpectationMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExpectationMode) Scan(value interface{}) error {
	if value == nil {
		ns.ExpectationMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExpectationMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExpectationMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExpectationMode), nil
}

type JobState string

const (
	JobStatePending   JobState = "pending"
	JobStateRunning   JobState = "running"
	JobStateDone      JobState = "done"
	JobStateFailed    JobState = "failed"
	JobStateCancelled JobState = "cancelled"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState
	Valid    bool // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

type OrgPlan string

const (
	OrgPlanFree       OrgPlan = "free"
	OrgPlanPilot      OrgPlan = "pilot"
	OrgPlanEntry      OrgPlan = "entry"
	OrgPlanMidmarket  OrgPlan = "midmarket"
	OrgPlanEnterprise OrgPlan = "enterprise"
)

func (e *OrgPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgPlan(s)
	case string:
		*e = OrgPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgPlan: %T", src)
	}
	return nil
}

type NullOrgPlan struct {
	OrgPlan OrgPlan
	Valid   bool // Valid is true if OrgPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgPlan) Scan(value interface{}) error {
	if value == nil {
		ns.OrgPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgPlan), nil
}

type PreTenancyKind string

const (
	PreTenancyKindSession         PreTenancyKind = "session"
	PreTenancyKindOidcFlow        PreTenancyKind = "oidc_flow"
	PreTenancyKindEmailDomain     PreTenancyKind = "email_domain"
	PreTenancyKindTenant          PreTenancyKind = "tenant"
	PreTenancyKindCollectorCert   PreTenancyKind = "collector_cert"
	PreTenancyKindEnrollmentToken PreTenancyKind = "enrollment_token"
)

func (e *PreTenancyKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PreTenancyKind(s)
	case string:
		*e = PreTenancyKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PreTenancyKind: %T", src)
	}
	return nil
}

type NullPreTenancyKind struct {
	PreTenancyKind PreTenancyKind
	Valid          bool // Valid is true if PreTenancyKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPreTenancyKind) Scan(value interface{}) error {
	if value == nil {
		ns.PreTenancyKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PreTenancyKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPreTenancyKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PreTenancyKind), nil
}

type Severity string

const (
	SeverityCritical Severity = "critical"
	SeverityHigh     Severity = "high"
	SeverityMedium   Severity = "medium"
	SeverityLow      Severity = "low"
	SeverityInfo     Severity = "info"
)

func (e *Severity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Severity(s)
	case string:
		*e = Severity(s)
	default:
		return fmt.Errorf("unsupported scan type for Severity: %T", src)
	}
	return nil
}

type NullSeverity struct {
	Severity Severity
	Valid    bool // Valid is true if Severity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.Severity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Severity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Severity), nil
}

type StateStatus string

const (
	StateStatusOk      StateStatus = "ok"
	StateStatusSoft    StateStatus = "soft"
	StateStatusHard    StateStatus = "hard"
	StateStatusUnknown StateStatus = "unknown"
)

func (e *StateStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StateStatus(s)
	case string:
		*e = StateStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StateStatus: %T", src)
	}
	return nil
}

type NullStateStatus struct {
	StateStatus StateStatus
	Valid       bool // Valid is true if StateStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStateStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StateStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StateStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStateStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StateStatus), nil
}

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleOperator UserRole = "operator"
	UserRoleViewer   UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VerifyOutcome string

const (
	VerifyOutcomePASS        VerifyOutcome = "PASS"
	VerifyOutcomeFAILURE     VerifyOutcome = "FAILURE"
	VerifyOutcomeDRIFT       VerifyOutcome = "DRIFT"
	VerifyOutcomeWARNING     VerifyOutcome = "WARNING"
	VerifyOutcomeUNKNOWN     VerifyOutcome = "UNKNOWN"
	VerifyOutcomeUNREACHABLE VerifyOutcome = "UNREACHABLE"
)

func (e *VerifyOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerifyOutcome(s)
	case string:
		*e = VerifyOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for VerifyOutcome: %T", src)
	}
	return nil
}

type NullVerifyOutcome struct {
	VerifyOutcome VerifyOutcome
	Valid         bool // Valid is true if VerifyOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerifyOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.VerifyOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerifyOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerifyOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerifyOutcome), nil
}

type Alert struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	EndpointID     pgtype.UUID
	DriftEventID   pgtype.UUID
	Severity       Severity
	SubReason      pgtype.Text
	Summary        string
	DedupeKey      string
	State          string
	AcknowledgedBy pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
}

type AlertDelivery struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	AlertID       pgtype.UUID
	Channel       string
	Status        string
	Attempts      int32
	LastError     pgtype.Text
	NextAttemptAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	DeliveredAt   pgtype.Timestamptz
}

type AuditEvent struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	ActorID    pgtype.UUID
	ActorKind  string
	Action     string
	ObjectKind pgtype.Text
	ObjectID   pgtype.UUID
	Detail     []byte
	SourceIp   *netip.Addr
	At         pgtype.Timestamptz
}

type Certificate struct {
	CredentialID       pgtype.UUID
	TenantID           pgtype.UUID
	Serial             pgtype.Text
	SubjectDn          pgtype.Text
	SubjectCn          pgtype.Text
	Sans               []string
	SansTruncatedCount int32
	IssuerDn           pgtype.Text
	IssuerCredentialID pgtype.UUID
	NotBefore          pgtype.Timestamptz
	NotAfter           pgtype.Timestamptz
	KeyAlgorithm       pgtype.Text
	KeySize            pgtype.Int4
	SelfSigned         bool
	ParseStatus        string
}

type Collector struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	Name                  string
	ClientCertFingerprint string
	Version               pgtype.Text
	ScopeDigest           pgtype.Text
	Status                CollectorStatus
	DeclaredCidrs         []netip.Prefix
	ReachableCidrs        []netip.Prefix
	LastSeenAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastHeartbeatAt       pgtype.Timestamptz
	ProtocolVersion       pgtype.Int4
	SpoolBytes            pgtype.Int8
	SpoolPctFull          pgtype.Float4
	TasksCompleted        pgtype.Int8
	TasksFailed           pgtype.Int8
	LastError             pgtype.Text
}

type CollectorCertificate struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	CollectorID    pgtype.UUID
	Fingerprint    string
	Serial         string
	SubjectCn      string
	NotBefore      pgtype.Timestamptz
	NotAfter       pgtype.Timestamptz
	CertificatePem string
	RevokedAt      pgtype.Timestamptz
	RevokedReason  pgtype.Text
	ReplacedBy     pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Credential struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Kind        CredentialKind
	Fingerprint string
	FirstSeen   pgtype.Timestamptz
	LastSeen    pgtype.Timestamptz
}

type DriftEvent struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	EndpointID        pgtype.UUID
	Kind              string
	FromStatus        NullStateStatus
	ToStatus          NullStateStatus
	Outcome           NullVerifyOutcome
	SubReason         pgtype.Text
	PreviousSubReason pgtype.Text
	Severity          Severity
	Summary           pgtype.Text
	Observations      int32
	DedupeKey         string
	At                pgtype.Timestamptz
}

type Endpoint struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	Hostname   string
	Port       int32
	Sni        string
	Source     string
	FirstSeen  pgtype.Timestamptz
	LastSeen   pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
}

type EndpointState struct {
	EndpointID        pgtype.UUID
	TenantID          pgtype.UUID
	Status            StateStatus
	Outcome           NullVerifyOutcome
	SubReason         pgtype.Text
	Severity          NullSeverity
	Consecutive       int32
	Threshold         int32
	Alerted           bool
	FirstObserved     pgtype.Timestamptz
	LastObserved      pgtype.Timestamptz
	LastChanged       pgtype.Timestamptz
	SoftSince         pgtype.Timestamptz
	NextCheckAt       pgtype.Timestamptz
	TotalObservations int64
	TotalHardEvents   int64
}

type EnrollmentToken struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	TokenHash       []byte
	CreatedBy       pgtype.UUID
	ExpiresAt       pgtype.Timestamptz
	UsedAt          pgtype.Timestamptz
	UsedByCollector pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}

type ExpectedState struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	EndpointID    pgtype.UUID
	Mode          ExpectationMode
	CredentialID  pgtype.UUID
	Policy        []byte
	Confirmed     bool
	ConfirmedBy   pgtype.UUID
	ConfirmedAt   pgtype.Timestamptz
	EffectiveFrom pgtype.Timestamptz
	Source        pgtype.Text
	IsCurrent     bool
	CreatedAt     pgtype.Timestamptz
}

type IdentityProvider struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Issuer          string
	ClientID        string
	ClientSecretEnc []byte
	EmailDomain     string
	Enabled         bool
	CreatedAt       pgtype.Timestamptz
}

type IngestBatch struct {
	TenantID     pgtype.UUID
	BatchID      string
	CollectorID  pgtype.UUID
	Observations int32
	AcceptedAt   pgtype.Timestamptz
}

type Job struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Kind        string
	EndpointID  pgtype.UUID
	State       JobState
	RunAfter    pgtype.Timestamptz
	Attempts    int32
	MaxAttempts int32
	LeasedUntil pgtype.Timestamptz
	LeasedBy    pgtype.Text
	LastError   pgtype.Text
	DedupeKey   string
	CreatedAt   pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
}

type JobRun struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	JobID      pgtype.UUID
	Attempt    int32
	Worker     pgtype.Text
	Outcome    string
	Detail     pgtype.Text
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type Mode2Nonce struct {
	TenantID    pgtype.UUID
	CollectorID pgtype.UUID
	Nonce       string
	ExpiresAt   pgtype.Timestamptz
}

type Observation struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	CredentialID pgtype.UUID
	EndpointID   pgtype.UUID
	CollectorID  pgtype.UUID
	Address      *netip.Addr
	Port         pgtype.Int4
	Source       string
	ObservedAt   pgtype.Timestamptz
}

type Organization struct {
	ID            pgtype.UUID
	Name          string
	Plan          OrgPlan
	EndpointQuota int32
	EmailDomain   pgtype.Text
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type PreTenancyLookup struct {
	Kind         PreTenancyKind
	LookupKey    string
	TenantID     pgtype.UUID
	SubjectID    pgtype.UUID
	Issuer       pgtype.Text
	ClientID     pgtype.Text
	EmailDomain  pgtype.Text
	ExpiresAt    pgtype.Timestamptz
	Refused      bool
	Nonce        pgtype.Text
	CodeVerifier pgtype.Text
	RedirectUri  pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type Session struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	UserID        pgtype.UUID
	TokenHash     []byte
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	IdleExpiresAt pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	UserAgent     pgtype.Text
	SourceIp      *netip.Addr
	RotatedTo     pgtype.UUID
}

type User struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	Email      string
	SsoSubject pgtype.Text
	SsoIssuer  pgtype.Text
	Role       UserRole
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
}

type VerificationResult struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	EndpointID      pgtype.UUID
	ExpectedStateID pgtype.UUID
	CollectorID     pgtype.UUID
	Outcome         VerifyOutcome
	SubReason       pgtype.Text
	Summary         pgtype.Text
	IpsResolved     []netip.Addr
	IpsChecked      []netip.Addr
	IpsMatching     []netip.Addr
	IpsUnreachable  []netip.Addr
	IpsTlsError     []netip.Addr
	IpsSkipped      []netip.Addr
	PartialRollout  bool
	Divergence      bool
	Suppressed      bool
	Alertable       bool
	PerIp           []byte
	RunID           pgtype.Text
	CheckedAt       pgtype.Timestamptz
}
