// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pretenancy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ptlActiveTenants = `-- name: PtlActiveTenants :many
SELECT t::text AS tenant FROM ptl_active_tenants() AS t
`

func (q *Queries) PtlActiveTenants(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, ptlActiveTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tenant string
		if err := rows.Scan(&tenant); err != nil {
			return nil, err
		}
		items = append(items, tenant)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ptlCollectorCert = `-- name: PtlCollectorCert :one
SELECT o_tenant::text AS tenant, o_collector::text AS collector_id,
       o_expires::timestamptz AS expires_at, o_revoked::boolean AS revoked
  FROM ptl_collector_cert($1::text)
`

type PtlCollectorCertRow struct {
	Tenant      string
	CollectorID string
	ExpiresAt   pgtype.Timestamptz
	Revoked     bool
}

func (q *Queries) PtlCollectorCert(ctx context.Context, fingerprint string) (PtlCollectorCertRow, error) {
	row := q.db.QueryRow(ctx, ptlCollectorCert, fingerprint)
	var i PtlCollectorCertRow
	err := row.Scan(
		&i.Tenant,
		&i.CollectorID,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const ptlConsumeOIDCFlow = `-- name: PtlConsumeOIDCFlow :one
SELECT o_nonce::text AS nonce, o_verifier::text AS code_verifier,
       o_redirect::text AS redirect_uri, o_issuer::text AS issuer,
       o_client::text AS client_id, o_domain::text AS email_domain,
       o_expires::timestamptz AS expires_at
  FROM ptl_consume_oidc_flow($1::text)
`

type PtlConsumeOIDCFlowRow struct {
	Nonce        string
	CodeVerifier string
	RedirectUri  string
	Issuer       string
	ClientID     string
	EmailDomain  string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) PtlConsumeOIDCFlow(ctx context.Context, state string) (PtlConsumeOIDCFlowRow, error) {
	row := q.db.QueryRow(ctx, ptlConsumeOIDCFlow, state)
	var i PtlConsumeOIDCFlowRow
	err := row.Scan(
		&i.Nonce,
		&i.CodeVerifier,
		&i.RedirectUri,
		&i.Issuer,
		&i.ClientID,
		&i.EmailDomain,
		&i.ExpiresAt,
	)
	return i, err
}

const ptlCreateOIDCFlow = `-- name: PtlCreateOIDCFlow :exec
SELECT ptl_create_oidc_flow($1::text, $2::text, $3::text,
       $4::text, $5::text, $6::text, $7::text,
       $8::timestamptz)
`

type PtlCreateOIDCFlowParams struct {
	State        string
	Nonce        string
	CodeVerifier string
	RedirectUri  string
	Issuer       string
	ClientID     string
	EmailDomain  string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) PtlCreateOIDCFlow(ctx context.Context, arg PtlCreateOIDCFlowParams) error {
	_, err := q.db.Exec(ctx, ptlCreateOIDCFlow,
		arg.State,
		arg.Nonce,
		arg.CodeVerifier,
		arg.RedirectUri,
		arg.Issuer,
		arg.ClientID,
		arg.EmailDomain,
		arg.ExpiresAt,
	)
	return err
}

const ptlEmailDomain = `-- name: PtlEmailDomain :one
SELECT o_tenant::text AS tenant, o_issuer::text AS issuer, o_client::text AS client_id
  FROM ptl_email_domain($1::text)
`

type PtlEmailDomainRow struct {
	Tenant   string
	Issuer   string
	ClientID string
}

func (q *Queries) PtlEmailDomain(ctx context.Context, domain string) (PtlEmailDomainRow, error) {
	row := q.db.QueryRow(ctx, ptlEmailDomain, domain)
	var i PtlEmailDomainRow
	err := row.Scan(&i.Tenant, &i.Issuer, &i.ClientID)
	return i, err
}

const ptlEnrollmentToken = `-- name: PtlEnrollmentToken :one
SELECT o_tenant::text AS tenant, o_expires::timestamptz AS expires_at,
       o_used::boolean AS used
  FROM ptl_enrollment_token($1::bytea)
`

type PtlEnrollmentTokenRow struct {
	Tenant    string
	ExpiresAt pgtype.Timestamptz
	Used      bool
}

func (q *Queries) PtlEnrollmentToken(ctx context.Context, tokenHash []byte) (PtlEnrollmentTokenRow, error) {
	row := q.db.QueryRow(ctx, ptlEnrollmentToken, tokenHash)
	var i PtlEnrollmentTokenRow
	err := row.Scan(&i.Tenant, &i.ExpiresAt, &i.Used)
	return i, err
}

const ptlSession = `-- name: PtlSession :one

SELECT o_tenant::text AS tenant, o_session::text AS session_id
  FROM ptl_session($1::bytea)
`

type PtlSessionRow struct {
	Tenant    string
	SessionID string
}

// Pre-tenancy routing. These are the ONLY queries that reach
// pre_tenancy_lookup, and they do so through the ptl_* functions — the
// application role has no privilege on the table itself.
func (q *Queries) PtlSession(ctx context.Context, tokenHash []byte) (PtlSessionRow, error) {
	row := q.db.QueryRow(ctx, ptlSession, tokenHash)
	var i PtlSessionRow
	err := row.Scan(&i.Tenant, &i.SessionID)
	return i, err
}
