// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	DueEndpoints(ctx context.Context, arg DueEndpointsParams) ([]string, error)
	// Scheduler. Runs inside a tenant transaction, so RLS scopes every row.
	// The endpoint id is cast to TEXT before NULLIF. In hand-written pgx,
	// NULLIF($3,'')::uuid had the parameter resolved as uuid and "" was rejected
	// before NULLIF ran; that broke twice.
	//
	// Measured, and recorded so nobody over-trusts it: in THIS statement, emitted
	// through sqlc, the un-cast form also works — sqlc types the parameter as
	// interface{} and PostgreSQL resolves it as text. So the cast below is not
	// enforced by the compiler or by sqlc, and removing it fails no test. It stays
	// because an explicit type is the defensive form, and
	// TestEnqueueWithNoEndpointStoresNullNotAnError pins the BEHAVIOUR (an empty
	// endpoint id stores NULL and does not error) whichever form is used.
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (string, error)
	PtlActiveTenants(ctx context.Context) ([]string, error)
	PtlCollectorCert(ctx context.Context, fingerprint string) (PtlCollectorCertRow, error)
	PtlConsumeOIDCFlow(ctx context.Context, state string) (PtlConsumeOIDCFlowRow, error)
	PtlCreateOIDCFlow(ctx context.Context, arg PtlCreateOIDCFlowParams) error
	PtlEmailDomain(ctx context.Context, domain string) (PtlEmailDomainRow, error)
	PtlEnrollmentToken(ctx context.Context, tokenHash []byte) (PtlEnrollmentTokenRow, error)
	// Pre-tenancy routing. These are the ONLY queries that reach
	// pre_tenancy_lookup, and they do so through the ptl_* functions — the
	// application role has no privilege on the table itself.
	PtlSession(ctx context.Context, tokenHash []byte) (PtlSessionRow, error)
	// History reads. Run inside a tenant transaction; RLS scopes every row.
	TransitionsForEndpoint(ctx context.Context, arg TransitionsForEndpointParams) ([]TransitionsForEndpointRow, error)
}

var _ Querier = (*Queries)(nil)
