// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sched.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO jobs (tenant_id, kind, endpoint_id, dedupe_key, run_after)
VALUES ($1::uuid, $2::text, NULLIF($3::text, '')::uuid,
        $4::text, $5::timestamptz)
ON CONFLICT DO NOTHING
RETURNING id::text
`

type EnqueueJobParams struct {
	TenantID   pgtype.UUID
	Kind       string
	EndpointID string
	DedupeKey  string
	RunAfter   pgtype.Timestamptz
}

// Scheduler. Runs inside a tenant transaction, so RLS scopes every row.
// The endpoint id is cast to TEXT before NULLIF. In hand-written pgx,
// NULLIF($3,”)::uuid had the parameter resolved as uuid and "" was rejected
// before NULLIF ran; that broke twice.
//
// Measured, and recorded so nobody over-trusts it: in THIS statement, emitted
// through sqlc, the un-cast form also works — sqlc types the parameter as
// interface{} and PostgreSQL resolves it as text. So the cast below is not
// enforced by the compiler or by sqlc, and removing it fails no test. It stays
// because an explicit type is the defensive form, and
// TestEnqueueWithNoEndpointStoresNullNotAnError pins the BEHAVIOUR (an empty
// endpoint id stores NULL and does not error) whichever form is used.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (string, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.TenantID,
		arg.Kind,
		arg.EndpointID,
		arg.DedupeKey,
		arg.RunAfter,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
